"""memory vector tables

Revision ID: 0001_memory_vector_tables
Revises: None
Create Date: 2025-12-12
"""

from __future__ import annotations

import sqlalchemy as sa  # type: ignore[import-not-found]

from alembic import op

revision = "0001_memory_vector_tables"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    op.create_table(
        "memory_items",
        # UUIDv7 stored as text (time-ordered, generated by uuid6.uuid7()).
        sa.Column("id", sa.Text(), primary_key=True, nullable=False),
        sa.Column("user_id", sa.Text(), nullable=False),
        sa.Column("avatar_id", sa.Text(), nullable=True),
        sa.Column("scope", sa.Text(), nullable=False),  # user | avatar
        sa.Column("kind", sa.Text(), nullable=False),  # card | chunk
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "embedding", sa.Text(), nullable=False
        ),  # pgvector via raw SQL in repository
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source_session_id", sa.Text(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
    )

    # HNSW index using inner product operator class.
    # Note: the "embedding" column is altered to vector(384) in the next op.execute so
    # SQLAlchemy
    # doesn't require pgvector type at migration time.
    op.execute(
        "ALTER TABLE memory_items ALTER COLUMN embedding "
        "TYPE vector(384) USING embedding::vector;"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS memory_items_embedding_hnsw_ip "
        "ON memory_items USING hnsw (embedding vector_ip_ops);"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS memory_items_user_avatar_kind "
        "ON memory_items (user_id, avatar_id, kind);"
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS memory_items_embedding_hnsw_ip;")
    op.execute("DROP INDEX IF EXISTS memory_items_user_avatar_kind;")
    op.drop_table("memory_items")
    op.execute("DROP EXTENSION IF EXISTS vector;")
